- hosts: localhost
  roles:
    - name: openstack-environment

- hosts: datastore
  gather_facts: no
  vars:
    ansible_user: centos
  tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:
    - name: gather facts
      setup:
    - name: Overwrite the DNS set by the DHCP, since it points on the local machine
      copy:
        dest: /etc/resolv.conf
        content: |
            nameserver 8.8.8.8
            nameserver 8.8.4.4
      become: true
    - import_role:
        name: vmware-ci-dnsmasq
    - import_role:
        name: vmware-ci-nfs-share

- hosts: "{{ prefix }}vcenter"
  gather_facts: no
  vars:
    ansible_user: root
    ansible_password: '!234AaAa56'
  tasks:
    - command: ifconfig eth0 mtu 1450
