- hosts: all
  tasks:
    - import_role:
        name: vmware-ci-write-etc-hosts
      vars:
        vmware_ci_write_etc_hosts_mapping:
          vcenter: '{{ hostvars.vcenter.ansible_host }}'
          esxi1: '{{ "esxi1" in hostvars and hostvars.esxi1.ansible_host }}'
          esxi2: '{{ "esxi2" in hostvars and hostvars.esxi2.ansible_host }}'
          esxi3: '{{ "esxi3" in hostvars and hostvars.esxi3.ansible_host }}'
          datastore: '{{ hostvars.datastore.ansible_host }}'

- hosts: datastore
  vars:
      ansible_user: centos
  tasks:
    - import_role:
        name: vmware-ci-nfs-share
      vars:
        vmware_ci_nfs_share_allow_ips:
          - 192.168.123.6
          - 192.168.123.7
