- hosts: localhost
  tasks:
    - set_fact:
        vmware_ci_set_passwords_passwords:
            root: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits,hexdigits') }}56"
            zuul: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits,hexdigits') }}56"

- hosts: all
  tasks:
    - import_role:
        name: vmware-ci-write-etc-hosts
      vars:
        vmware_ci_write_etc_hosts_mapping:
          vcenter: '{{ hostvars.vcenter.ansible_host }}'
          esxi1: '{{ "esxi1" in hostvars and hostvars.esxi1.ansible_host }}'
          esxi2: '{{ "esxi2" in hostvars and hostvars.esxi2.ansible_host }}'
          esxi3: '{{ "esxi3" in hostvars and hostvars.esxi3.ansible_host }}'
          datastore: '{{ hostvars.datastore.ansible_host }}'
    - import_role:
        name: vmware-ci-set-passwords

- hosts: vcenter
  gather_facts: false
  tasks:
    - import_role:
        name: configure-swap
      vars:
        configure_swap_current_total: 0
        configure_swap_size: 2000
    - import_role:
        name: vmware-ci-vcenter-services

- hosts: datastore
  vars:
      ansible_user: centos
  tasks:
    - import_role:
        name: vmware-ci-nfs-share
      vars:
        vmware_ci_nfs_share_allow_ips: "{{ groups['esxis'] | map('extract', hostvars, ['ansible_host'])|list }}"
