- hosts: datastore
  vars:
      ansible_user: centos
  tasks:
    - import_role:
        name: vmware-ci-nfs-share
      vars:
        vmware_ci_nfs_share_allow_ips:
          - 192.168.123.6
          - 192.168.123.7
