- os_network:
    state: present
    name: "{{ prefix }}testlab"
    port_security_enabled: true
- os_subnet:
    state: present
    network_name: "{{ prefix }}testlab"
    name: "{{ prefix }}testlabsubnet"
    cidr: '{{ openstack_environment_testlab_network_cidr }}'
    enable_dhcp: true
    gateway_ip: "{{ openstack_environment_hosts.gateway|ipaddr('address') }}"
    dns_nameservers:
#        #      - "{{ openstack_environment_hosts.dns|ipaddr('address') }}"
      - 8.8.8.8
- os_network:
    state: present
    name: "{{ prefix }}testlabdummy"
    port_security_enabled: true
- os_subnet:
    state: present
    network_name: "{{ prefix }}testlabdummy"
    name: "{{ prefix }}testlabdummysubnet"
    cidr: 192.168.10.0/24
    enable_dhcp: true
- os_networks_info:
    interface: public
  register: networks
- os_router:
    state: present
    name: "{{ prefix }}router_lab"
    network: '{{ (networks.openstack_networks|selectattr("router:external")|first)["id"] }}'
    interfaces:
      - "{{ prefix }}testlabsubnet"
- os_security_group:
    name: ssh
    state: present
- os_security_group_rule:
    security_group: ssh
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
#- os_port:
#    state: present
#    name: "{{ prefix }}port_lab_datastore"
#    network: "{{ prefix }}testlab"
#    security_groups:
#      - default
#      - ssh
#    fixed_ips:
#      - ip_address: "{{ openstack_environment_hosts.datastore|ipaddr('address') }}"
#- os_port:
#    state: present
#    name: "{{ prefix }}port_lab_vcsa"
#    network: "{{ prefix }}testlab"
#    fixed_ips:
#      - ip_address: "{{ openstack_environment_hosts['vcsa']|ipaddr('address') }}"
#
#- os_port:
#    state: present
#    name: "{{ prefix }}port_lab_esxi1"
#    network: "{{ prefix }}testlab"
#    fixed_ips:
#      - ip_address: "{{ openstack_environment_hosts.esxi1|ipaddr('address') }}"
#- os_port:
#    state: present
#    name: "{{ prefix }}port_lab_esxi2"
#    network: "{{ prefix }}testlab"
#    fixed_ips:
#      - ip_address: "{{ openstack_environment_hosts.esxi2|ipaddr('address') }}"

- name: launch the datastore node
  os_server:
    name: "{{ prefix }}datastore"
    state: present
    image: '{{ openstack_environment_datastore_vm_image }}'
    boot_from_volume: True
    terminate_volume: yes
    flavor: m1.small
    nics:
      - net-name: "{{ prefix }}testlab"
      #   - port-name: "{{ prefix }}port_lab_datastore"
    key_name: goneri
    auto_ip: true
    security_groups:
      - default
      - ssh
  register: datastore_info
- debug: var=datastore_info

- name: launch the vcenter instance
  os_server:
    name: "{{ prefix }}vcenter"
    state: present
    image: '{{ openstack_environment_vcsa_vm_image }}'
    boot_from_volume: true
    terminate_volume: yes
    flavor_ram: 8000
    key_name: goneri
    config_drive: true
    #    auto_ip: false
    timeout: 600
    nics:
      - net-name: "{{ prefix }}testlab"
    security_groups:
      - default
      - ssh
      - https
    userdata: |
      #cloud-config
      hostname: vcenter.test
      fqdn: vcenter.test
#      chpasswd:
#        expire: false
#        list: 'root:!234AaAa56'
#      disable_root: false
#      password: '!234AaAa56'



- name: launch the ESXi instances
  os_server:
    name: "{{ prefix }}{{ item.name }}"
    state: present
    image: "{{ item.image }}"
    boot_from_volume: True
    terminate_volume: yes
    flavor_ram: "{{ item.flavor_ram }}"
    key_name: goneri
    config_drive: true
    auto_ip: false
    timeout: 600
    nics:
      - net-name: "{{ prefix }}testlab"
      #- port-name: "{{ prefix }}{{ item.port }}"
      - net-name: "{{ prefix }}testlabdummy"
    userdata: |
      #cloud-config
      hostname: "{{ item.name }}"
      fqdn: "{{ item.name }}"
      chpasswd:
        expire: false
        list: 'root:!234AaAa56'
      disable_root: false
      password: '!234AaAa56'
      resize_rootfs: true
  with_items:
    - name: esxi1
      port: port_lab_esxi1
      flavor_ram: 4096
      image: '{{ openstack_environment_esxi_vm_image }}'
    - name: esxi2
      port: port_lab_esxi2
      flavor_ram: 4096
      image: '{{ openstack_environment_esxi_vm_image }}'

- name: refresh inventory
  meta: refresh_inventory

