# https://bugs.launchpad.net/nova/+bug/1759420
- hosts: localhost
  roles:
    - name: openstack-environment

- hosts: datastore
  gather_facts: no
  vars:
    ansible_user: centos
  tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:
    - name: gather facts
      setup:
    - import_role:
        name: vmware-ci-nfs-share
    - import_role:
        name: vmware-ci-proxy
    - import_role:
        name: vmware-ci-dns

- hosts: localhost
  tasks:
    - name: Open the proxy port forwarding
      command: 'ssh -L 8888:127.0.0.1:8888 -fN centos@{{ hostvars.datastore.ansible_host }}'
    - name: Start ntpd setting for an ESXi Host
      vmware_host_service_manager:
        hostname: '{{ item }}'
        username: root
        password: '!234AaAa56'
        proxy_host: 127.0.0.1
        proxy_port: 8888
        esxi_hostname: '{{ item }}'
        validate_certs: false
        service_name: ntpd
        state: present
      with_items:
          - esxi1
          - esxi2
    - name: Set NTP setting for all ESXi Host in given Cluster
      vmware_host_ntp:
        hostname: '{{ item }}'
        username: root
        password: '!234AaAa56'
        proxy_host: 127.0.0.1
        proxy_port: 8888
        esxi_hostname: '{{ item }}'
        validate_certs: false
        state: present
        ntp_servers:
            - 0.pool.ntp.org
            - 1.pool.ntp.org
      with_items:
          - esxi1
          - esxi2

#- hosts: datastore
#  vars:
#    vcenter_validate_certs: False
#    gather_facts: False
#    vcsa_ip: '192.168.123.90'
#    datastore_name: local
#    ansible_user: centos
#    vmware_proxy_host: '127.0.0.1'
#    vmware_proxy_port: 8888
#  tasks:
#  - copy:
#      src: ~/Downloads/VMware-VCSA-all-6.7.0-14367737.iso
#      dest: ~/Downloads/
#  - import_role:
#      name: vcenter-instance
#    vars:
#      vcenter_instance:
#        installation:
#          from: 'iso'
#          iso_path: "{{ '~/Downloads/VMware-VCSA-all-6.7.0-14367737.iso' | expanduser }}"
#        network:  # IP Configuration of the vcenter
#          address: '{{ vcsa_ip }}'
#          prefix: 24
#          gateway: 192.168.123.1
#          dns: 192.168.123.4
#          hostname: vcenter.test
#        esxi:
#          hostname: '{{ hostvars["esxi-vcenter"].ansible_host }}'
#          username: root
#          password: '!234AaAa56'
