- hosts: localhost
  tasks:
    - import_role:
        name: vmware-ci-configure-ansible-test
      vars:
        # The location of a copy of ansible-2.10
        vmware_ci_configure_ansible_test_ansible_path: /home/goneri/git_repos/ansible_projects/ansible-2.10
    - import_role:
        name: ansible-test-inventory
      vars:
        ansible_test_inventory_os: vmware_rest

    - import_role:
        name: ansible-test
      vars:
        ansible_test_location: ~/.ansible/collections/ansible_collections/community/vmware/
        ansible_test_integration_targets: zuul/vmware/vcenter_2esxi/
        ansible_test_venv_path: /home/goneri/tmp/vl
        ansible_test_collections: true
        ansible_test_ansible_path: /home/goneri/git_repos/ansible_projects/c
        ansible_test_split_in: 4
        ansible_test_enable_ara: false
        ansible_test_collection_name: vmware
        ansible_test_collection_namespace: community
